name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test:unit
      env:
        CI: true
deploy:

    runs-on: ubuntu-latest
    
    steps:
      - name: SCP Files
        uses: appleboy/scp-action@v0.0.1
       env:
          HOST: 87.236.22.136
          USERNAME: root
          PORT: 22
          SOURCE: /var/www/html/footbal-planner/
          TARGET: ./dist/*
          secrets: ${{ secrets.shh_key }}
        
      

  
